# postgres-secret.yaml
# file containing secrets for postgresql and pgadmin implementations
# every portion of text in encoded with base64 -> to obtain the enconded [string] : echo -n "[string]" | base64
apiVersion: v1
data:
  POSTGRES_DB: U2lsYXNEQg==               # SilasDB
  POSTGRES_PASSWORD: U2lsYXNQVw==         # SilasPW
  POSTGRES_USER: U2lsYXNBZG1pbg==         # SilasAdmin
  REPLICATION_PASSWORD: U2lsYXNSUFc=      # SilasRPW
  REPLICATION_USER: U2lsYXNBZG1pbg==      # SilasAdmin 
  PGADMIN_EMAIL: c2lsYXNAcGdhZG1pbi5jb20= # silas@pgadmin.com
kind: Secret
metadata:
  name: postgres-secret
  # namespace: postgres-ns
type: Opaque
