"""update field definitions

Revision ID: 608dd9f26ba3
Revises: f8de2437c354
Create Date: 2024-02-29 08:54:33.308986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '608dd9f26ba3'
down_revision: Union[str, None] = 'f8de2437c354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('broker', sa.String(), nullable=True))
    op.add_column('company', sa.Column('domiciled', sa.String(), nullable=True))
    op.add_column('metrics', sa.Column('policy_limit', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('metrics', sa.Column('gct_cpy', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('metrics', sa.Column('gct_cat', sa.Numeric(precision=10, scale=2), nullable=True))
    op.alter_column('metrics', 'property_damage',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('metrics', 'number_of_claims',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('metrics', 'aop_deductible',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('metrics', 'bi_deductible',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('metrics', 'tech_price',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('metrics', 'aal',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.drop_column('metrics', 'gwp')
    op.drop_column('metrics', 'gross_claims_total_non_cat')
    op.drop_column('metrics', 'tca')
    op.drop_column('metrics', 'gross_claims_total_cat')
    op.drop_column('metrics', 'gct_total_current_year')
    op.drop_column('metrics', 'gc_perc_nwp')
    op.drop_column('metrics', 'nwp')
    op.drop_column('metrics', 'gc_perc_gwp')
    op.drop_column('metrics', 'aal_perc_gwp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('aal_perc_gwp', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('metrics', sa.Column('gc_perc_gwp', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('metrics', sa.Column('nwp', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('metrics', sa.Column('gc_perc_nwp', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('metrics', sa.Column('gct_total_current_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('metrics', sa.Column('gross_claims_total_cat', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('metrics', sa.Column('tca', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('metrics', sa.Column('gross_claims_total_non_cat', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('metrics', sa.Column('gwp', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('metrics', 'aal',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('metrics', 'tech_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('metrics', 'bi_deductible',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('metrics', 'aop_deductible',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('metrics', 'number_of_claims',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('metrics', 'property_damage',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('metrics', 'gct_cat')
    op.drop_column('metrics', 'gct_cpy')
    op.drop_column('metrics', 'policy_limit')
    op.drop_column('company', 'domiciled')
    op.drop_column('company', 'broker')
    # ### end Alembic commands ###
