version: "3.8"

services:
  database:
    build: ./database
    container_name: silas-db
    healthcheck:
        test: ["CMD-SHELL", "psql -U healthcheck_user -d silastech -c 'SELECT 1 FROM silas.company LIMIT 1'"]
        interval: 10s
        retries: 5
        start_period: 30s
    env_file:
      - .env
    ports: 
      - "5432:5432"
    volumes:
    - ./db-data/:/var/lib/postgresql/data/
  
  backend:
    build: ./backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DOCKER_ENV=true
    depends_on:
      database:
        condition: service_healthy
    container_name: silas-backend
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./backend/app:/app
    ports:
      - 8000:8000

  frontend:
    build: ./frontend/silas-react
    depends_on:
      - backend
    container_name: silas-frontend
    ports:
      - "8080:8080"
