# pgadmin-secret.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
 name: pgadmin-secret 
data:
  pgadmin-password: YWRtaW4=              # echo -n "admin" | base64
  #pgadmin-email: dXNlckBkb21haW4uY29t   # echo -n "user@domain.com" | base64
  pgadmin-email: YWRtaW4=