export const metricsLabels = {
    gwp: 'Gross Written Premium',
    nwp: 'Net Written Premium',
    loss_ratio: 'Loss Ratio %',
    base_rate: 'Base Rate %',
    rate_change: 'Rate Change %',
    business_interruption: 'Business Interruption',
    property_damage: 'Property Damage',
    tiv: 'Total Insured Value',
    policy_limit: 'Policy Limit',
    claims_total: 'Claims Total',
    modelled_results_aal: 'Modelled Results (AAL)',
    fees_and_commissions: 'Fees and Commissions',
    brokerage: 'Brokerage',
    gct_perc_gwp: 'Gross Claims Total as % of Gross Written Premium',
    gct_perc_nwp: 'Gross Claims Total as % of Net Written Premium',
    bi_deductible: 'BI Deductible (Days)',
    aop_deductible: 'AOP Deductible',
    aal: 'AAL',
    aal_perc_gwp: 'AAL as % of GWP',
    tech_price:'Technical Premium',
    technical_adequacy: 'Technical Adequacy %',
    avg_rate_change:'Average Rate Change',
    rate_on_tiv: 'Rate on TIV',
    rate_on_line: 'Rate on Line'
  };