"""adds metrics table

Revision ID: a89ff553f405
Revises: bab45c4244c8
Create Date: 2024-02-28 22:29:12.208680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a89ff553f405'
down_revision: Union[str, None] = 'bab45c4244c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tiv', sa.Integer(), nullable=True),
    sa.Column('gwp', sa.Integer(), nullable=True),
    sa.Column('base_rate', sa.Integer(), nullable=True),
    sa.Column('brokerage', sa.Integer(), nullable=True),
    sa.Column('fees_and_commissions', sa.Integer(), nullable=True),
    sa.Column('nwp', sa.Integer(), nullable=True),
    sa.Column('number_of_claims', sa.Integer(), nullable=True),
    sa.Column('property_damage', sa.Integer(), nullable=True),
    sa.Column('gross_claims_total_cat', sa.Integer(), nullable=True),
    sa.Column('gross_claims_total_non_cat', sa.Integer(), nullable=True),
    sa.Column('gct_total_current_year', sa.Integer(), nullable=True),
    sa.Column('gc_perc_gwp', sa.Integer(), nullable=True),
    sa.Column('gc_perc_nwp', sa.Integer(), nullable=True),
    sa.Column('bi_deductible', sa.Integer(), nullable=True),
    sa.Column('aal_perc_gwp', sa.Integer(), nullable=True),
    sa.Column('tca', sa.String(), nullable=True),
    sa.Column('tech_price', sa.Integer(), nullable=True),
    sa.Column('aop_deductible', sa.Integer(), nullable=True),
    sa.Column('aal', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_metrics')
    # ### end Alembic commands ###
