"""fix wrong table name

Revision ID: f8de2437c354
Revises: 9d353f16ba8b
Create Date: 2024-02-28 22:37:48.842477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8de2437c354'
down_revision: Union[str, None] = '9d353f16ba8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('tiv', sa.Integer(), nullable=True),
    sa.Column('gwp', sa.Integer(), nullable=True),
    sa.Column('base_rate', sa.Integer(), nullable=True),
    sa.Column('brokerage', sa.Integer(), nullable=True),
    sa.Column('fees_and_commissions', sa.Integer(), nullable=True),
    sa.Column('nwp', sa.Integer(), nullable=True),
    sa.Column('number_of_claims', sa.Integer(), nullable=True),
    sa.Column('property_damage', sa.Integer(), nullable=True),
    sa.Column('gross_claims_total_cat', sa.Integer(), nullable=True),
    sa.Column('gross_claims_total_non_cat', sa.Integer(), nullable=True),
    sa.Column('gct_total_current_year', sa.Integer(), nullable=True),
    sa.Column('gc_perc_gwp', sa.Integer(), nullable=True),
    sa.Column('gc_perc_nwp', sa.Integer(), nullable=True),
    sa.Column('bi_deductible', sa.Integer(), nullable=True),
    sa.Column('aal_perc_gwp', sa.Integer(), nullable=True),
    sa.Column('tca', sa.String(), nullable=True),
    sa.Column('tech_price', sa.Integer(), nullable=True),
    sa.Column('aop_deductible', sa.Integer(), nullable=True),
    sa.Column('aal', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('company_metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tiv', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gwp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('base_rate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('brokerage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fees_and_commissions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nwp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('number_of_claims', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('property_damage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gross_claims_total_cat', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gross_claims_total_non_cat', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gct_total_current_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gc_perc_gwp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gc_perc_nwp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bi_deductible', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aal_perc_gwp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tca', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tech_price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aop_deductible', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='company_metrics_company_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='company_metrics_pkey')
    )
    op.drop_table('metrics')
    # ### end Alembic commands ###
